services:
  cabinet-frontend:
    image: ghcr.io/roon9e/bedolaga-cabinet:latest
    container_name: cabinet_frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bot_network

networks:
  bot_network:
    external: true
    name: remnawave-bedolaga-telegram-bot_bot_network